# Generated by Django 5.1.4 on 2026-04-24 21:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_account_display_name_institution_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('simplefin', 'SimpleFIN'), ('manual', 'Manual entry')], max_length=20)),
                ('broker', models.CharField(blank=True, help_text='e.g., Fidelity, Robinhood. Free text.', max_length=200)),
                ('name', models.CharField(help_text='Provider name for SimpleFIN accounts; user-entered for manual.', max_length=200)),
                ('display_name', models.CharField(blank=True, default='', help_text='UI override; never overwritten by sync.', max_length=200)),
                ('external_id', models.CharField(blank=True, default='', help_text="Provider's account ID (SimpleFIN only).", max_length=200)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to='banking.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', help_text="Human-readable name, e.g. 'Apple Inc.'", max_length=200)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('market_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_basis_source', models.CharField(choices=[('auto', 'Auto (from provider)'), ('manual', 'Manual (user-entered)')], default='auto', max_length=10)),
                ('external_id', models.CharField(blank=True, default='', help_text="Provider's holding ID (SimpleFIN); blank for manual.", max_length=200)),
                ('last_priced_at', models.DateTimeField(blank=True, null=True)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.investmentaccount')),
            ],
            options={
                'ordering': ['investment_account', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='investments.investmentaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('institution', 'external_id'), name='uniq_inv_account_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('investment_account', 'external_id'), name='uniq_holding_per_account_by_external_id'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', '')), fields=('investment_account', 'symbol'), name='uniq_manual_holding_per_symbol'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.UniqueConstraint(fields=('investment_account', 'date'), name='uniq_snapshot_per_account_per_day'),
        ),
    ]
