# Generated by Django 5.1.4 on 2026-04-25 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Uninvested cash sitting in this account. Maintained manually.', max_digits=18),
        ),
    ]
