# Generated by Django 5.1.4 on 2026-04-24 22:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('scraped', 'Scraped from URL'), ('manual', 'Manual value')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=16)),
                ('unit', models.CharField(blank=True, default='', help_text="'oz', 'each', etc. Optional.", max_length=20)),
                ('source_url', models.URLField(blank=True, default='')),
                ('css_selector', models.CharField(blank=True, default='', help_text='Optional. Blank = auto-detect first $-prefixed price on the page.', max_length=500)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('last_priced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.asset')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
