# Generated by Django 5.1.4 on 2026-04-24 20:51

import apps.banking.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly label for this connection.', max_length=200)),
                ('provider', models.CharField(choices=[('simplefin', 'SimpleFIN')], default='simplefin', max_length=20)),
                ('access_url', apps.banking.fields.EncryptedTextField(help_text='Provider access URL. Encrypted at rest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('loan', 'Loan'), ('other', 'Other')], default='other', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('org_name', models.CharField(blank=True, help_text="Institution name from provider (e.g., 'Chase').", max_length=200)),
                ('external_id', models.CharField(help_text="Provider's account ID; used as the upsert key.", max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.institution')),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('pending', models.BooleanField(default=False)),
                ('external_id', models.CharField(help_text="Provider's txn ID; upsert key.", max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('institution', 'external_id'), name='uniq_account_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='uniq_txn_per_account'),
        ),
    ]
