# Generated by Django 5.1.4 on 2026-04-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional override shown in the UI. Blank = use name. Never overwritten by sync.', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional override shown in the UI. Blank = use name. Never overwritten by sync.', max_length=200),
        ),
    ]
