# Generated by Django 5.1.4 on 2026-04-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_display_name_institution_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional override shown in the UI. Blank = use payee/description. Never overwritten by sync.', max_length=200),
        ),
    ]
